name: Detect Terraform Drift

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      force_slack:
        type: boolean
        default: false
        description: "Post to Slack even without drift (manual runs only)"

jobs:
  detect-drift:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_REGION: us-east-1
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify backend (S3 + DynamoDB)
        run: |
          aws s3 ls s3://tf-state-l00187927 >/dev/null
          aws dynamodb describe-table --table-name terraform-locks --query 'Table.TableStatus' >/dev/null

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false   # <- important: get real -detailed-exitcode

      - name: Terraform Init (uses remote S3 backend)
        run: terraform init -input=false

      # --- Plan: capture real exit code and full output ---
      - name: Terraform Plan for Drift Detection
        id: plan
        run: |
          set +e
          terraform plan -input=false -no-color -detailed-exitcode -out=tfplan.out | tee plan.txt
          PLAN_EXIT=${PIPESTATUS[0]}
          echo "PLAN_EXIT=$PLAN_EXIT" >> $GITHUB_ENV
          {
            echo "PLAN_OUTPUT<<EOF"
            cat plan.txt
            echo "EOF"
          } >> $GITHUB_ENV
          set -e

      - name: Show plan result
        if: always()
        run: |
          echo "PLAN_EXIT=${PLAN_EXIT:-unset}"
          printf "%s\n" "${PLAN_OUTPUT:-no output captured}" | tail -n 200
          {
            echo "### Terraform plan"
            echo "- Exit code: ${PLAN_EXIT:-unset}"
            echo ""
            echo "Last 200 lines:"
            echo '```'
            printf "%s\n" "${PLAN_OUTPUT:-no output captured}" | tail -n 200
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Build a summary of changes for Slack (counts + top 30 resources)
      - name: Summarize drift (JSON)
        if: env.PLAN_EXIT == '2' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_slack == 'true')
        run: |
          # Create JSON plan; if show fails for any reason, keep an empty JSON so jq doesn't break
          terraform show -json tfplan.out > plan.json || echo '{}' > plan.json

          # Counts summary (add | change | destroy | replace)
          DRIFT_SUMMARY=$(jq -r '
            def action(a):
              if a==["create"] then "add"
              elif a==["update"] then "change"
              elif a==["delete"] then "destroy"
              elif a==["delete","create"] or a==["create","delete"] then "replace"
              else (a|join("+"))
              end;
            (.resource_changes // [])
            | (reduce (.[]?.change.actions | action) as $k ({}; .[$k] = (.[ $k ] // 0) + 1))
            | ["add","change","destroy","replace"]
            | map("\(.): \((inputs)[. ] // 0)") as $o
            | ($o[0] // "add: 0") + " | " + ($o[1] // "change: 0") + " | " + ($o[2] // "destroy: 0") + " | " + ($o[3] // "replace: 0")
          ' plan.json plan.json plan.json plan.json plan.json)
          echo "DRIFT_SUMMARY=${DRIFT_SUMMARY:-add: 0 | change: 0 | destroy: 0 | replace: 0}" >> $GITHUB_ENV

          # Top 30 changed resources
          {
            echo "DRIFT_LIST<<EOF"
            jq -r '
              def action(a):
                if a==["create"] then "add"
                elif a==["update"] then "change"
                elif a==["delete"] then "destroy"
                elif a==["delete","create"] or a==["create","delete"] then "replace"
                else (a|join("+"))
                end;
              (.resource_changes // [])
              | [ .[] | "*\(.address)* — \(.change.actions | action)" ]
              | .[0:30]
              | if length==0 then "No resource changes." else join("\n") end
            ' plan.json
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Send Slack Notification if Drift Detected
        if: env.PLAN_EXIT == '2' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_slack == 'true')
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
        run: |
          jq -n \
            --arg channel "$SLACK_CHANNEL_ID" \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg sha "$SHA" \
            --arg run_url "$RUN_URL" \
            --arg summary "$DRIFT_SUMMARY" \
            --arg changes "$DRIFT_LIST" \
            '{
              channel: $channel,
              text: "⚠️ Terraform drift detected. Approve remediation?",
              blocks: [
                { "type": "header", "text": { "type": "plain_text", "text": "⚠️ Drift detected", "emoji": true } },
                { "type": "section", "fields": [
                  { "type": "mrkdwn", "text": "*Repo:*\n\($repo)" },
                  { "type": "mrkdwn", "text": "*Branch:*\n\($branch)" },
                  { "type": "mrkdwn", "text": "*Commit:*\n`\($sha)`" },
                  { "type": "mrkdwn", "text": "*Run:*\n<\($run_url)|Open>" }
                ]},
                { "type": "section", "text": { "type": "mrkdwn", "text": "*Summary:*\n\($summary)" } },
                { "type": "section", "text": { "type": "mrkdwn", "text": "*Changes (top 30):*\n\($changes)" } },
                { "type": "divider" },
                { "type": "section", "text": { "type": "mrkdwn", "text": "Approve remediation?" } },
                { "type": "actions", "elements": [
                  { "type": "button", "text": { "type": "plain_text", "text": "Approve ✅" }, "style": "primary", "action_id": "approve_remediation", "value": "approve" },
                  { "type": "button", "text": { "type": "plain_text", "text": "Reject ❌" }, "style": "danger", "action_id": "reject_remediation", "value": "reject" }
                ]}
              ]
            }' > payload.json

          curl -sS -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
            -H "Content-type: application/json; charset=utf-8" \
            --data @payload.json | tee /tmp/slack_response.json

          jq -e '.ok == true' /tmp/slack_response.json > /dev/null
