name: Detect Terraform Drift

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      force_slack:
        type: boolean
        default: false
        description: "Post to Slack even without drift"

concurrency:
  group: drift-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: "us-east-1"
  TF_DIR: "terraform"
  SLACK_CHANNEL: "C097WJUFJCU"
  OIDC_ROLE_ARN: "arn:aws:iam::147997134125:role/GitHubTerraformPlanRole"

jobs:
  detect:
    name: Detect & Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC AssumeRole)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y pipx jq
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Who am I (sanity)
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false  # preserve detailed exit codes

      - name: Terraform init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -input=false -no-color

      - name: Plan (refresh-only, detailed exit code)
        id: plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          set +e
          terraform plan -refresh-only -detailed-exitcode -lock-timeout=2m -out=tfplan.out -no-color -input=false
          code=$?
          echo "exitcode=$code" >> $GITHUB_OUTPUT
          if [ $code -eq 1 ]; then
            echo '{}' > plan.json
            echo 'Plan failed; created empty plan.json for diagnostics.'
            sha="$(sha256sum plan.json | awk '{print $1}')"
            echo "drift_id=${sha::12}-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
            exit 0
          fi
          terraform show -no-color tfplan.out > plan.txt
          terraform show -json tfplan.out > plan.json
          sha="$(sha256sum plan.json | awk '{print $1}')"
          echo "drift_id=${sha::12}-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
          exit 0

      - name: Debug plan exit code
        run: echo "Plan exit code was:${{ steps.plan.outputs.exitcode }}"

      - name: Upload plan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ steps.plan.outputs.drift_id }}
          path: |
            ${{ env.TF_DIR }}/tfplan.out
            ${{ env.TF_DIR }}/plan.txt
            ${{ env.TF_DIR }}/plan.json
          retention-days: 7

      - name: Install Checkov (CIS scan)
        run: pipx install checkov

      - name: Run Checkov
        id: checkov
        run: |
          checkov -d "$TF_DIR" -o json > checkov.json || true
          # Handle both Checkov 2.x (object) and 3.x (array) JSON
          fails=$(jq -r '
            if type=="array" then
              map((.results.failed_checks // []) | length) | add
            else
              (.results.failed_checks // []) | length
            end' checkov.json 2>/dev/null || echo 0)
          warns=$(jq -r '
            if type=="array" then
              ( (map((.results.parsing_errors // []) | length) | add)
                + (map((.results.resource_skipped_checks // []) | length) | add) )
            else
              (((.results.parsing_errors // []) | length)
                + ((.results.resource_skipped_checks // []) | length))
            end' checkov.json 2>/dev/null || echo 0)
          echo "failed=${fails}" >> $GITHUB_OUTPUT
          echo "warned=${warns}" >> $GITHUB_OUTPUT

      - name: Upload Checkov report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-${{ steps.plan.outputs.drift_id }}
          path: checkov.json
          retention-days: 7

      # === UPDATED: robust counts + fallback to plan.txt; drift_id carried in action_id ===
      - name: Build Slack payload
        if: ${{ steps.plan.outputs.exitcode == '2' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_slack == 'true') }}
        id: payload
        env:
          DRIFT_ID: ${{ steps.plan.outputs.drift_id }}
          EXIT: ${{ steps.plan.outputs.exitcode }}
          FAILS: ${{ steps.checkov.outputs.failed }}
          WARNS: ${{ steps.checkov.outputs.warned }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # 1) Try JSON-based counts (handles replace actions too)
          summary="$(jq -r '
            (.resource_changes // [])
            | reduce .[] as $rc (
                {adds:0, changes:0, destroys:0};
                .adds     += (( $rc.change.actions // [] | index("create") )  | if .==null then 0 else 1 end)
              | .changes  += (( $rc.change.actions // [] | index("update") )  | if .==null then 0 else 1 end)
              | .destroys += (( $rc.change.actions // [] | index("delete") )  | if .==null then 0 else 1 end)
            )' "$TF_DIR/plan.json")"
          adds=$(echo "$summary" | jq -r .adds)
          changes=$(echo "$summary" | jq -r .changes)
          destroys=$(echo "$summary" | jq -r .destroys)

          # JSON-derived lists (top 10)
          creates_list_json=$(jq -r '
            [(.resource_changes // [])[]
             | select((.change.actions // []) | index("create"))
             | .address] | .[0:10]
            | if length==0 then "" else map("• `" + . + "`") | join("\n") end
          ' "$TF_DIR/plan.json")

          updates_list_json=$(jq -r '
            [(.resource_changes // [])[]
             | select((.change.actions // []) | index("update"))
             | .address] | .[0:10]
            | if length==0 then "" else map("• `" + . + "`") | join("\n") end
          ' "$TF_DIR/plan.json")

          deletes_list_json=$(jq -r '
            [(.resource_changes // [])[]
             | select((.change.actions // []) | index("delete"))
             | .address] | .[0:10]
            | if length==0 then "" else map("• `" + . + "`") | join("\n") end
          ' "$TF_DIR/plan.json")

          # 2) If JSON shows all zeros, fall back to parsing plan.txt for resource-level +/-/~
          total=$((adds + changes + destroys))
          if [ "$total" -eq 0 ]; then
            creates_txt=$(grep -E '^[[:space:]]*\+ resource "' "$TF_DIR/plan.txt" | sed -E 's/^ *\+ resource "([^"]+)" "([^"]+)".*$/\1.\2/' | head -n 10 || true)
            updates_txt=$(grep -E '^[[:space:]]*~ resource "' "$TF_DIR/plan.txt" | sed -E 's/^ *~ resource "([^"]+)" "([^"]+)".*$/\1.\2/' | head -n 10 || true)
            deletes_txt=$(grep -E '^[[:space:]]*- resource "' "$TF_DIR/plan.txt" | sed -E 's/^ *- resource "([^"]+)" "([^"]+)".*$/\1.\2/' | head -n 10 || true)

            adds=$(printf "%s\n" "$creates_txt" | grep -c . || echo 0)
            changes=$(printf "%s\n" "$updates_txt" | grep -c . || echo 0)
            destroys=$(printf "%s\n" "$deletes_txt" | grep -c . || echo 0)

            # Bullet formatting (or 'none')
            if [ -n "$creates_txt" ]; then creates_list=$(printf "%s\n" "$creates_txt" | sed 's/^/• `/' | sed 's/$/`/'); else creates_list="none"; fi
            if [ -n "$updates_txt" ]; then updates_list=$(printf "%s\n" "$updates_txt" | sed 's/^/• `/' | sed 's/$/`/'); else updates_list="none"; fi
            if [ -n "$deletes_txt" ]; then deletes_list=$(printf "%s\n" "$deletes_txt" | sed 's/^/• `/' | sed 's/$/`/'); else deletes_list="none"; fi
          else
            # Use JSON lists if JSON counts found anything
            creates_list="${creates_list_json:-none}"
            updates_list="${updates_list_json:-none}"
            deletes_list="${deletes_list_json:-none}"
          fi

          # Short diff excerpt (first ~30 change lines)
          diff_snippet="$(grep -E '^[[:space:]]*[~+-]' "$TF_DIR/plan.txt" | head -n 30)"

          # Build payload with jq (interpolation only)
          jq -n \
            --arg channel "$SLACK_CHANNEL" \
            --arg drift "$DRIFT_ID" \
            --arg runurl "$RUN_URL" \
            --arg fails "$FAILS" \
            --arg warns "$WARNS" \
            --arg adds "$adds" \
            --arg changes "$changes" \
            --arg destroys "$destroys" \
            --arg creates "$creates_list" \
            --arg updates "$updates_list" \
            --arg deletes "$deletes_list" \
            --arg diff "$diff_snippet" \
            '
            {
              channel: $channel,
              text: "Terraform drift detected",
              blocks: [
                { "type": "header", "block_id": ("drift::" + $drift), "text": { "type": "plain_text", "text": "Terraform Drift Detected" } },
                { "type": "section", "fields": [
                    { "type": "mrkdwn", "text": "*Drift ID:*\n\($drift)" },
                    { "type": "mrkdwn", "text": "*Repo/Run:*\n<\($runurl)|Open run>" }
                  ]},
                { "type": "section", "fields": [
                    { "type": "mrkdwn", "text": "*Adds:* \($adds)" },
                    { "type": "mrkdwn", "text": "*Changes:* \($changes)" },
                    { "type": "mrkdwn", "text": "*Destroys:* \($destroys)" }
                  ]},
                { "type": "section", "text": { "type": "mrkdwn", "text": ("*Creates (up to 10):*\n\($creates)") } },
                { "type": "section", "text": { "type": "mrkdwn", "text": ("*Updates (up to 10):*\n\($updates)") } },
                { "type": "section", "text": { "type": "mrkdwn", "text": ("*Deletes (up to 10):*\n\($deletes)") } },
                { "type": "section", "text": { "type": "mrkdwn", "text": ("*Plan snippet:*\n```\($diff)```") } },
                { "type": "context", "elements": [
                    { "type": "mrkdwn", "text": "*CIS pre-check:* \($fails) failing checks, \($warns) warnings" }
                  ]},
                { "type": "actions", "elements": [
                    { "type": "button",
                      "text": { "type": "plain_text", "text": "Approve Remediation" }, "style": "primary",
                      "action_id": ("approve_remediation::" + $drift), "value": "approve" },
                    { "type": "button",
                      "text": { "type": "plain_text", "text": "Reject" }, "style": "danger",
                      "action_id": ("reject_remediation::" + $drift), "value": "reject" }
                  ]}
              ]
            }' > payload.json

      - name: Post to Slack
        if: steps.payload.outcome == 'success'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -sS -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
            -H "Content-type: application/json; charset=utf-8" \
            --data @payload.json | tee /tmp/slack_response.json
          jq -e '.ok == true' /tmp/slack_response.json > /dev/null

      - name: No drift (exit=0)
        if: ${{ steps.plan.outputs.exitcode == '0' && !(github.event_name == 'workflow_dispatch' && github.event.inputs.force_slack == 'true') }}
        run: echo "No drift."
